version: "3.9"

services:
  app:
    build: .
    container_name: ws_app
    environment:
      # Database
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      # MinIO
      MINIO_INTERNAL_URL: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SYSTEM_BUCKET: ${MINIO_SYSTEM_BUCKET}
      MINIO_CLIENT_BUCKET: ${MINIO_CLIENT_BUCKET}
      MINIO_CLIENT_PUBLIC_ACCESS: ${MINIO_CLIENT_PUBLIC_ACCESS}
      # App params
      BATCH_LIMIT: ${BATCH_LIMIT}
      CLEAN_OUTPUT_ON_START: ${CLEAN_OUTPUT_ON_START}
      COMMIT_RESULTS: ${COMMIT_RESULTS}
      SCHEDULER_INTERVAL_MINUTES: ${SCHEDULER_INTERVAL_MINUTES}
      OUTPUT_FOLDER: /app/src/image_moderator/output
      MODEL_PATH: /app/src/image_moderator/models/license-plate-finetune-v1l.onnx
    volumes:
      - app_output:/app/src/image_moderator/output
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    networks:
      - backend


volumes:
  pg_data:
  minio_data:
  app_output:

networks:
  backend:
    external: true